[project]
name = "rag-system"
version = "0.1.0"
description = "Personal RAG system"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "python-multipart",

    "streamlit",
    "httpx",

    "langchain",
    "langchain-community",
    "langchain-openai",
    "langchain-chroma",
    "langchain-text-splitters",
    "langgraph",
    "chromadb",

    "pdfplumber",
    "python-dotenv",
    "tiktoken",
]

[dependency-groups]
client = [
    "streamlit",
    "httpx",
]